-- ============================================================
-- PARTE 1: ESTADOS Y USUARIOS
-- ============================================================

CREATE TABLE IF NOT EXISTS "HOT_CLICK_ESTADO_TB" (
  "ID_ESTADO" integer PRIMARY KEY,
  "NOMBRE_ESTADO" varchar(20) NOT NULL,
  "DESCRIPCION" varchar(100),
  "CODIGO_COLOR" varchar(7)
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_USUARIO_TB" (
  "ID_USUARIO" SERIAL PRIMARY KEY,
  "IDENTIFICACION" varchar(20) UNIQUE NOT NULL,
  "NOMBRE" varchar(50) NOT NULL,
  "APELLIDO_PATERNO" varchar(50) NOT NULL,
  "APELLIDO_MATERNO" varchar(50),
  "CORREO" varchar(100) UNIQUE NOT NULL,
  "TELEFONO" varchar(20) NOT NULL,
  "TELEFONO_ALTERNO" varchar(20),
  "CONTRASENA_HASH" varchar(255) NOT NULL,
  "FOTO_PERFIL_URL" varchar(500),
  "FECHA_REGISTRO" timestamp DEFAULT CURRENT_TIMESTAMP,
  "FECHA_ULTIMO_ACCESO" timestamp,
  "INTENTOS_FALLIDOS" integer DEFAULT 0,
  "BLOQUEADO_HASTA" timestamp,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_ROL_TB" (
  "ID_ROL" SERIAL PRIMARY KEY,
  "NOMBRE_ROL" varchar(30) UNIQUE NOT NULL,
  "DESCRIPCION" varchar(200),
  "NIVEL_ACCESO" integer NOT NULL DEFAULT 1,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_USUARIO_ROL_TB" (
  "FK_ID_USUARIO" integer NOT NULL,
  "FK_ID_ROL" integer NOT NULL,
  "FECHA_ASIGNACION" timestamp DEFAULT CURRENT_TIMESTAMP,
  "ASIGNADO_POR" integer,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1,
  PRIMARY KEY ("FK_ID_USUARIO", "FK_ID_ROL")
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_PERMISO_TB" (
  "ID_PERMISO" SERIAL PRIMARY KEY,
  "NOMBRE_PERMISO" varchar(50) UNIQUE NOT NULL,
  "DESCRIPCION" varchar(200),
  "MODULO" varchar(30) NOT NULL,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_ROL_PERMISO_TB" (
  "FK_ID_ROL" integer NOT NULL,
  "FK_ID_PERMISO" integer NOT NULL,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1,
  PRIMARY KEY ("FK_ID_ROL", "FK_ID_PERMISO")
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_SESION_TB" (
  "ID_SESION" BIGSERIAL PRIMARY KEY,
  "TOKEN" varchar(500) NOT NULL,
  "IP_ADDRESS" varchar(45) NOT NULL,
  "USER_AGENT" text,
  "FECHA_INICIO" timestamp DEFAULT CURRENT_TIMESTAMP,
  "FECHA_FIN" timestamp,
  "FK_ID_USUARIO" integer NOT NULL,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_TIPO_OTP_TB" (
  "ID_TIPO_OTP" SERIAL PRIMARY KEY,
  "NOMBRE" varchar(30) NOT NULL,
  "TIEMPO_EXPIRACION_SEG" integer NOT NULL DEFAULT 300,
  "LONGITUD_CODIGO" integer NOT NULL DEFAULT 6,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_CODIGO_OTP_TB" (
  "ID_OTP_CODE" BIGSERIAL PRIMARY KEY,
  "CODIGO_HASH" varchar(255) NOT NULL,
  "EXPIRES_AT" timestamp NOT NULL,
  "USED_AT" timestamp,
  "ATTEMPTS" integer DEFAULT 0,
  "ACTIVE_FLAG" boolean DEFAULT true,
  "FK_ID_USUARIO" integer NOT NULL,
  "FK_ID_TIPO_OTP" integer NOT NULL,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_USUARIO_DIRECCION_TB" (
  "ID_DIRECCION" SERIAL PRIMARY KEY,
  "DETALLES_DIRECCION" text NOT NULL,
  "LATITUD" decimal(10,8),
  "LONGITUD" decimal(11,8),
  "ES_PRINCIPAL" boolean DEFAULT false,
  "TIPO_DIRECCION" varchar(20) DEFAULT 'ENVIO',
  "FK_ID_USUARIO" integer NOT NULL,
  "FK_ID_DISTRITO" integer,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);


-- ============================================================
-- PARTE 2: CONFIGURACION Y UBICACIONES
-- ============================================================

CREATE TABLE IF NOT EXISTS "HOT_CLICK_CONFIGURACION_MONEDA_TB" (
  "ID_CONFIG_MONEDA" SERIAL PRIMARY KEY,
  "MONEDA_DEFECTO" varchar(3) DEFAULT 'CRC',
  "SIMBOLO_MONEDA" varchar(5) DEFAULT '₡',
  "DECIMALES" integer DEFAULT 0,
  "SEPARADOR_MILES" varchar(1) DEFAULT ',',
  "PRECIO_MINIMO" integer DEFAULT 0,
  "PRECIO_MAXIMO" integer DEFAULT 1000000,
  "PRECIO_PROMEDIO" integer DEFAULT 15000,
  "FK_ID_ADMIN_CLIENTE" integer NOT NULL,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_CONFIGURACION_IMPUESTO_TB" (
  "ID_CONFIG_IMPUESTO" SERIAL PRIMARY KEY,
  "NOMBRE_IMPUESTO" varchar(50) DEFAULT 'IVA',
  "PORCENTAJE_IMPUESTO" decimal(5,2) DEFAULT 13,
  "APLICAR_IMPUESTO" boolean DEFAULT false,
  "EXENTO_POR_DEFECTO" boolean DEFAULT false,
  "TIPO_CALCULO" varchar(20) DEFAULT 'PORCENTAJE',
  "MONTO_FIJO" integer,
  "FK_ID_ADMIN_CLIENTE" integer NOT NULL,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1,
  "FECHA_ACTUALIZACION" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_RANGO_PRECIO_TB" (
  "ID_RANGO" SERIAL PRIMARY KEY,
  "NOMBRE_RANGO" varchar(30) NOT NULL,
  "PRECIO_MINIMO" integer NOT NULL,
  "PRECIO_MAXIMO" integer NOT NULL,
  "DESCRIPCION" varchar(200),
  "COLOR_ETIQUETA" varchar(7),
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_PAIS_TB" (
  "ID_PAIS" SERIAL PRIMARY KEY,
  "NOMBRE_PAIS" varchar(100) NOT NULL,
  "CODIGO_ISO2" char(2) NOT NULL,
  "CODIGO_ISO3" char(3) NOT NULL,
  "CODIGO_TELEFONICO" varchar(5) NOT NULL,
  "MONEDA" varchar(3) NOT NULL,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_PROVINCIA_TB" (
  "ID_PROVINCIA" SERIAL PRIMARY KEY,
  "NOMBRE_PROVINCIA" varchar(100) NOT NULL,
  "FK_ID_PAIS" integer NOT NULL,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_CANTON_TB" (
  "ID_CANTON" SERIAL PRIMARY KEY,
  "NOMBRE_CANTON" varchar(100) NOT NULL,
  "FK_ID_PROVINCIA" integer NOT NULL,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_DISTRITO_TB" (
  "ID_DISTRITO" SERIAL PRIMARY KEY,
  "NOMBRE_DISTRITO" varchar(100) NOT NULL,
  "CODIGO_POSTAL" varchar(10),
  "FK_ID_CANTON" integer NOT NULL,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_BARRIO_TB" (
  "ID_BARRIO" SERIAL PRIMARY KEY,
  "NOMBRE_BARRIO" varchar(100) NOT NULL,
  "FK_ID_DISTRITO" integer NOT NULL,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_COORDENADA_UBICACION_TB" (
  "ID_COORDENADA" SERIAL PRIMARY KEY,
  "LATITUD" decimal(10,8) NOT NULL,
  "LONGITUD" decimal(11,8) NOT NULL,
  "REFERENCIA" text,
  "FK_ID_DISTRITO" integer,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);


-- ============================================================
-- PARTE 3: BODEGAS Y CATEGORIAS
-- ============================================================

CREATE TABLE IF NOT EXISTS "HOT_CLICK_BODEGA_TB" (
  "ID_BODEGA" SERIAL PRIMARY KEY,
  "NOMBRE_BODEGA" varchar(100) NOT NULL,
  "DIRECCION_EXACTA" text NOT NULL,
  "TELEFONO" varchar(20) NOT NULL,
  "CORREO_CONTACTO" varchar(100),
  "HORARIO_APERTURA" time,
  "HORARIO_CIERRE" time,
  "LATITUD" decimal(10,8),
  "LONGITUD" decimal(11,8),
  "CAPACIDAD_MAXIMA" integer,
  "ENCARGADO_NOMBRE" varchar(100),
  "FK_ID_ADMIN_CLIENTE" integer NOT NULL,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1,
  "FECHA_CREACION" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_BODEGA_UBICACION_TB" (
  "FK_ID_BODEGA" integer NOT NULL,
  "FK_ID_DISTRITO" integer NOT NULL,
  "FK_ID_BARRIO" integer,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1,
  PRIMARY KEY ("FK_ID_BODEGA", "FK_ID_DISTRITO")
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_BODEGA_USUARIO_TB" (
  "FK_ID_BODEGA" integer NOT NULL,
  "FK_ID_USUARIO" integer NOT NULL,
  "CARGO" varchar(50),
  "FECHA_ASIGNACION" timestamp DEFAULT CURRENT_TIMESTAMP,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1,
  PRIMARY KEY ("FK_ID_BODEGA", "FK_ID_USUARIO")
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_BODEGA_HISTORIAL_TB" (
  "ID_HISTORIAL_BODEGA" SERIAL PRIMARY KEY,
  "CAMPO_MODIFICADO" varchar(50),
  "VALOR_ANTERIOR" text,
  "VALOR_NUEVO" text,
  "FECHA_CAMBIO" timestamp DEFAULT CURRENT_TIMESTAMP,
  "FK_ID_BODEGA" integer NOT NULL,
  "FK_ID_USUARIO" integer NOT NULL,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_CATEGORIA_TB" (
  "ID_CATEGORIA" SERIAL PRIMARY KEY,
  "NOMBRE_CATEGORIA" varchar(100) NOT NULL,
  "DESCRIPCION" varchar(300),
  "IMAGEN_URL" varchar(500),
  "ORDEN_DISPLAY" integer DEFAULT 0,
  "FK_ID_CATEGORIA_PADRE" integer,
  "FK_ID_ADMIN_CLIENTE" integer NOT NULL,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_ETIQUETA_TB" (
  "ID_ETIQUETA" SERIAL PRIMARY KEY,
  "NOMBRE_ETIQUETA" varchar(50) UNIQUE NOT NULL,
  "COLOR_ETIQUETA" varchar(7),
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_PRODUCTO_ETIQUETA_TB" (
  "FK_ID_PRODUCTO" integer NOT NULL,
  "FK_ID_ETIQUETA" integer NOT NULL,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1,
  PRIMARY KEY ("FK_ID_PRODUCTO", "FK_ID_ETIQUETA")
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_CATEGORIA_ETIQUETA_TB" (
  "FK_ID_CATEGORIA" integer NOT NULL,
  "FK_ID_ETIQUETA" integer NOT NULL,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1,
  PRIMARY KEY ("FK_ID_CATEGORIA", "FK_ID_ETIQUETA")
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_MARCA_TB" (
  "ID_MARCA" SERIAL PRIMARY KEY,
  "NOMBRE_MARCA" varchar(100) UNIQUE NOT NULL,
  "LOGO_URL" varchar(500),
  "FK_ID_ADMIN_CLIENTE" integer NOT NULL,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);



-- ============================================================
-- PARTE 4: PRODUCTOS
-- ============================================================

CREATE TABLE IF NOT EXISTS "HOT_CLICK_PRODUCTO_TB" (
  "ID_PRODUCTO" SERIAL PRIMARY KEY,
  "NOMBRE_PRODUCTO" varchar(200) NOT NULL,
  "DESCRIPCION_CORTA" varchar(300),
  "DESCRIPCION_LARGA" text,
  "PRECIO_COMPRA" integer NOT NULL,
  "PRECIO_VENTA" integer NOT NULL,
  "MARGEN_GANANCIA" decimal(8,2),
  "ROI_PORCENTAJE" decimal(8,2),
  "COSTO_ENVIO_ESTIMADO" integer,
  "COSTO_ALMACENAJE" integer,
  "LINK_AMAZON" varchar(500),
  "STOCK_ACTUAL" integer NOT NULL DEFAULT 0,
  "STOCK_MINIMO" integer NOT NULL DEFAULT 5,
  "STOCK_MAXIMO" integer,
  "UNIDAD_MEDIDA" varchar(20) DEFAULT 'UNIDAD',
  "PESO_EN_GRAMOS" integer,
  "DIMENSIONES" json,
  "SKU" varchar(50) UNIQUE NOT NULL,
  "MARCA" varchar(100),
  "MODELO" varchar(100),
  "RANGO_PRECIO" varchar(20),
  "ES_UNICO" boolean NOT NULL DEFAULT false,
  "VENDIDO" boolean NOT NULL DEFAULT false,
  "DESTACADO" boolean NOT NULL DEFAULT false,
  "VISIBLE_CATALOGO" boolean NOT NULL DEFAULT true,
  "FK_ID_BODEGA" integer NOT NULL,
  "FK_ID_CATEGORIA" integer NOT NULL,
  "FK_ID_MARCA" integer,
  "FK_ID_ADMIN_CLIENTE" integer NOT NULL,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1,
  "FECHA_CREACION" timestamp DEFAULT CURRENT_TIMESTAMP,
  "FECHA_ULTIMA_COMPRA" date,
  "PROVEEDOR_PRINCIPAL" varchar(100),
  "TIEMPO_REORDEN_DIAS" integer DEFAULT 7
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_PRODUCTO_IMAGEN_TB" (
  "ID_IMAGEN" SERIAL PRIMARY KEY,
  "URL_IMAGEN" varchar(500) NOT NULL,
  "PUBLIC_ID_CLOUDINARY" varchar(200),
  "POSICION" integer DEFAULT 0,
  "ES_PRINCIPAL" boolean DEFAULT false,
  "ALT_TEXT" varchar(200),
  "FK_ID_PRODUCTO" integer NOT NULL,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_PRODUCTO_VIDEO_TB" (
  "ID_VIDEO" SERIAL PRIMARY KEY,
  "URL_VIDEO" varchar(500) NOT NULL,
  "PLATAFORMA" varchar(20) DEFAULT 'YOUTUBE',
  "EMBED_CODE" text,
  "POSICION" integer DEFAULT 0,
  "FK_ID_PRODUCTO" integer NOT NULL,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_PRODUCTO_ATRIBUTO_TB" (
  "ID_ATRIBUTO" SERIAL PRIMARY KEY,
  "NOMBRE_ATRIBUTO" varchar(50) NOT NULL,
  "TIPO_DATO" varchar(20) DEFAULT 'TEXTO',
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_PRODUCTO_ATRIBUTO_VALOR_TB" (
  "ID_VALOR_ATRIBUTO" SERIAL PRIMARY KEY,
  "VALOR" varchar(100) NOT NULL,
  "CODIGO_REFERENCIA" varchar(30),
  "FK_ID_ATRIBUTO" integer NOT NULL,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_PRODUCTO_ATRIBUTO_ASIGNACION_TB" (
  "ID_ASIGNACION_ATRIBUTO" SERIAL PRIMARY KEY,
  "PRECIO_ADICIONAL" integer DEFAULT 0,
  "STOCK_POR_ATRIBUTO" integer DEFAULT 0,
  "PESO_ADICIONAL_GRAMOS" integer DEFAULT 0,
  "FK_ID_PRODUCTO" integer NOT NULL,
  "FK_ID_VALOR_ATRIBUTO" integer NOT NULL,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_PRODUCTO_VARIANTE_TB" (
  "ID_VARIANTE" SERIAL PRIMARY KEY,
  "SKU_VARIANTE" varchar(50) UNIQUE NOT NULL,
  "PRECIO_VENTA_VARIANTE" integer NOT NULL,
  "STOCK_VARIANTE" integer DEFAULT 0,
  "FK_ID_PRODUCTO" integer NOT NULL,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_PRODUCTO_VARIANTE_ATRIBUTO_TB" (
  "FK_ID_VARIANTE" integer NOT NULL,
  "FK_ID_VALOR_ATRIBUTO" integer NOT NULL,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1,
  PRIMARY KEY ("FK_ID_VARIANTE", "FK_ID_VALOR_ATRIBUTO")
);


-- ============================================================
-- PARTE 5: ANALISIS Y SUGERENCIAS
-- ============================================================

CREATE TABLE IF NOT EXISTS "HOT_CLICK_ANALISIS_PRODUCTO_TB" (
  "ID_ANALISIS" BIGSERIAL PRIMARY KEY,
  "FECHA_ANALISIS" date NOT NULL,
  "VELOCIDAD_VENTA" decimal(10,2),
  "ROTACION_INVENTARIO" decimal(10,2),
  "DIAS_INVENTARIO_RESTANTE" integer,
  "PUNTO_REORDEN" integer,
  "CANTIDAD_SUGERIDA_COMPRA" integer,
  "MARGEN_CONTRIBUCION" integer,
  "PUNTO_EQUILIBRIO_UNIDADES" integer,
  "RENTABILIDAD_NETA" integer,
  "PORCENTAJE_RENTABILIDAD" decimal(8,2),
  "SCORE_RENTABILIDAD" integer,
  "CATEGORIA_ABC" varchar(1),
  "FK_ID_PRODUCTO" integer NOT NULL,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_SUGERENCIA_COMPRA_TB" (
  "ID_SUGERENCIA" BIGSERIAL PRIMARY KEY,
  "TIPO_SUGERENCIA" varchar(30),
  "TITULO" varchar(200) NOT NULL,
  "DESCRIPCION" text NOT NULL,
  "IMPACTO_ESTIMADO" integer,
  "PRIORIDAD" integer DEFAULT 1,
  "URL_REFERENCIA" varchar(500),
  "PRECIO_SUGERIDO" integer,
  "CANTIDAD_SUGERIDA" integer,
  "INVERSION_REQUERIDA" integer,
  "RETORNO_ESTIMADO" integer,
  "VISTO" boolean DEFAULT false,
  "APLICADO" boolean DEFAULT false,
  "FECHA_GENERACION" timestamp DEFAULT CURRENT_TIMESTAMP,
  "FK_ID_ADMIN_CLIENTE" integer NOT NULL,
  "FK_ID_PRODUCTO" integer,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_SUGERENCIA_CLIENTE_TB" (
  "ID_SUGERENCIA_CLIENTE" BIGSERIAL PRIMARY KEY,
  "TIPO_SUGERENCIA" varchar(30) NOT NULL,
  "MOTIVO" varchar(200),
  "SCORE_RELEVANCIA" decimal(5,2) DEFAULT 1.0,
  "FECHA_GENERACION" timestamp DEFAULT CURRENT_TIMESTAMP,
  "ACTIVO" boolean DEFAULT true,
  "FK_ID_USUARIO_FINAL" integer,
  "FK_ID_PRODUCTO_BASE" integer,
  "FK_ID_PRODUCTO_SUGERIDO" integer NOT NULL,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_FILTRO_ADMIN_TB" (
  "ID_FILTRO" SERIAL PRIMARY KEY,
  "NOMBRE_FILTRO" varchar(100) NOT NULL,
  "DESCRIPCION" varchar(200),
  "MODULO" varchar(30) NOT NULL,
  "CRITERIOS_JSON" jsonb NOT NULL,
  "ES_FAVORITO" boolean DEFAULT false,
  "FECHA_CREACION" timestamp DEFAULT CURRENT_TIMESTAMP,
  "FK_ID_ADMIN_CLIENTE" integer NOT NULL,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_HISTORIAL_CLIENTE_TB" (
  "ID_HISTORIAL" BIGSERIAL PRIMARY KEY,
  "TOTAL_COMPRAS" integer DEFAULT 0,
  "MONTO_TOTAL_GASTADO" integer DEFAULT 0,
  "PRIMERA_COMPRA" timestamp,
  "ULTIMA_COMPRA" timestamp,
  "PRODUCTO_FAVORITO" varchar(200),
  "CATEGORIA_FAVORITA" varchar(100),
  "PROMEDIO_COMPRA" integer DEFAULT 0,
  "FECHA_ACTUALIZACION" timestamp DEFAULT CURRENT_TIMESTAMP,
  "FK_ID_USUARIO_FINAL" integer NOT NULL UNIQUE,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_PROVEEDOR_TB" (
  "ID_PROVEEDOR" SERIAL PRIMARY KEY,
  "NOMBRE_PROVEEDOR" varchar(100) NOT NULL,
  "CONTACTO_NOMBRE" varchar(100),
  "TELEFONO" varchar(20),
  "CORREO" varchar(100),
  "SITIO_WEB" varchar(200),
  "DIRECCION" text,
  "TIEMPO_ENTREGA_DIAS" integer DEFAULT 7,
  "CALIDAD_PUNTUACION" integer DEFAULT 5,
  "PRECIO_COMPETITIVIDAD" integer DEFAULT 5,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_PRODUCTO_PROVEEDOR_TB" (
  "FK_ID_PRODUCTO" integer NOT NULL,
  "FK_ID_PROVEEDOR" integer NOT NULL,
  "PRECIO_COMPRA_ACTUAL" integer,
  "PRECIO_COMPRA_ANTERIOR" integer,
  "FECHA_ULTIMA_COMPRA" date,
  "ES_PROVEEDOR_PRINCIPAL" boolean DEFAULT false,
  "TIEMPO_ENTREGA_REAL" integer,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1,
  PRIMARY KEY ("FK_ID_PRODUCTO", "FK_ID_PROVEEDOR")
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_ALERTA_NEGOCIO_TB" (
  "ID_ALERTA" BIGSERIAL PRIMARY KEY,
  "TIPO_ALERTA" varchar(30),
  "MENSAJE" text NOT NULL,
  "NIVEL_URGENCIA" varchar(20),
  "LEIDA" boolean DEFAULT false,
  "FECHA_ALERTA" timestamp DEFAULT CURRENT_TIMESTAMP,
  "FK_ID_ADMIN_CLIENTE" integer NOT NULL,
  "FK_ID_PRODUCTO" integer,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_CONFIGURACION_ANALISIS_TB" (
  "ID_CONFIG" SERIAL PRIMARY KEY,
  "DIAS_HISTORICO_ANALISIS" integer DEFAULT 90,
  "UMBRAL_STOCK_CRITICO" integer DEFAULT 10,
  "MARGEN_MINIMO_RECOMENDADO" decimal(8,2) DEFAULT 30,
  "VELOCIDAD_VENTA_MINIMA" decimal(10,2) DEFAULT 1,
  "DIAS_ALERTA_REORDEN" integer DEFAULT 5,
  "FK_ID_ADMIN_CLIENTE" integer NOT NULL
);


-- ============================================================
-- PARTE 6: INVENTARIO Y CARRITO
-- ============================================================

CREATE TABLE IF NOT EXISTS "HOT_CLICK_TIPO_MOVIMIENTO_TB" (
  "ID_TIPO_MOVIMIENTO" SERIAL PRIMARY KEY,
  "NOMBRE" varchar(50) NOT NULL,
  "SIGNO" char(1) NOT NULL,
  "AFECTA_STOCK" boolean DEFAULT true,
  "DESCRIPCION" varchar(200),
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_MOVIMIENTO_INVENTARIO_TB" (
  "ID_MOVIMIENTO" BIGSERIAL PRIMARY KEY,
  "CANTIDAD" integer NOT NULL,
  "MOTIVO" text,
  "DOCUMENTO_REFERENCIA" varchar(100),
  "FECHA_MOVIMIENTO" timestamp DEFAULT CURRENT_TIMESTAMP,
  "COSTO_UNITARIO_MOMENTO" integer NOT NULL,
  "FK_ID_PRODUCTO" integer NOT NULL,
  "FK_ID_TIPO_MOVIMIENTO" integer NOT NULL,
  "FK_ID_USUARIO" integer NOT NULL,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_INVENTARIO_PERIODICO_TB" (
  "ID_INVENTARIO_PERIODICO" SERIAL PRIMARY KEY,
  "FECHA_INICIO" date NOT NULL,
  "FECHA_FIN" date NOT NULL,
  "TOTAL_INVERSION" integer DEFAULT 0,
  "TOTAL_VALOR_VENTA" integer DEFAULT 0,
  "FECHA_CIERRE" timestamp DEFAULT CURRENT_TIMESTAMP,
  "FK_ID_ADMIN_CLIENTE" integer NOT NULL,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_INVENTARIO_PRODUCTO_PERIODICO_TB" (
  "ID_INVENTARIO_PRODUCTO_PERIODICO" SERIAL PRIMARY KEY,
  "CANTIDAD_INICIAL" integer DEFAULT 0,
  "ENTRADAS" integer DEFAULT 0,
  "SALIDAS" integer DEFAULT 0,
  "CANTIDAD_FINAL" integer DEFAULT 0,
  "COSTO_PROMEDIO" integer DEFAULT 0,
  "FK_ID_PRODUCTO" integer NOT NULL,
  "FK_ID_INVENTARIO_PERIODICO" integer NOT NULL,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_CARRITO_TB" (
  "ID_CARRITO" SERIAL PRIMARY KEY,
  "FECHA_CREACION" timestamp DEFAULT CURRENT_TIMESTAMP,
  "FECHA_ACTUALIZACION" timestamp DEFAULT CURRENT_TIMESTAMP,
  "TOTAL_CARRITO" integer DEFAULT 0,
  "ESTADO_CARRITO" varchar(20) DEFAULT 'ACTIVO',
  "FK_ID_USUARIO_FINAL" integer NOT NULL,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_CARRITO_ITEM_TB" (
  "ID_CARRITO_ITEM" SERIAL PRIMARY KEY,
  "CANTIDAD" integer NOT NULL DEFAULT 1,
  "PRECIO_UNITARIO_MOMENTO" integer NOT NULL,
  "FK_ID_CARRITO" integer NOT NULL,
  "FK_ID_PRODUCTO" integer NOT NULL,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_CARRITO_DESCUENTO_TB" (
  "ID_DESCUENTO_CARRITO" SERIAL PRIMARY KEY,
  "CODIGO_CUPON" varchar(30) NOT NULL,
  "MONTO_DESCUENTO" integer DEFAULT 0,
  "TIPO_DESCUENTO" varchar(20) NOT NULL,
  "FK_ID_CARRITO" integer NOT NULL,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);



-- ============================================================
-- PARTE 7: PEDIDOS Y FACTURACION
-- ============================================================

CREATE SEQUENCE IF NOT EXISTS seq_pedido START 1000;

CREATE TABLE IF NOT EXISTS "HOT_CLICK_PEDIDO_TB" (
  "ID_PEDIDO" BIGSERIAL PRIMARY KEY,
  "NUMERO_PEDIDO" varchar(20) UNIQUE NOT NULL DEFAULT ('ORD-' || NEXTVAL('seq_pedido')),
  "FECHA_PEDIDO" timestamp DEFAULT CURRENT_TIMESTAMP,
  "FECHA_ENTREGA_ESTIMADA" date,
  "FECHA_ENTREGA_REAL" date,
  "SUBTOTAL" integer NOT NULL,
  "DESCUENTO_TOTAL" integer DEFAULT 0,
  "APLICA_IMPUESTO" boolean DEFAULT false,
  "MONTO_IMPUESTO" integer DEFAULT 0,
  "TOTAL_PEDIDO" integer NOT NULL,
  "COSTO_ENVIO" integer DEFAULT 0,
  "COSTO_TOTAL_PRODUCTOS" integer NOT NULL,
  "UTILIDAD_BRUTA" integer NOT NULL,
  "MARGEN_GANANCIA_PEDIDO" decimal(8,2),
  "ESTADO_PEDIDO" varchar(20) DEFAULT 'PENDIENTE',
  "METODO_PAGO" varchar(30) NOT NULL,
  "METODO_ENVIO" varchar(30) NOT NULL,
  "NOTAS" text,
  "FACTURA_GENERADA" boolean DEFAULT false,
  "FACTURA_ENVIADA_WHATSAPP" boolean DEFAULT false,
  "FK_ID_USUARIO_FINAL" integer NOT NULL,
  "FK_ID_BODEGA" integer NOT NULL,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_PEDIDO_ITEM_TB" (
  "ID_PEDIDO_ITEM" BIGSERIAL PRIMARY KEY,
  "CANTIDAD" integer NOT NULL,
  "PRECIO_UNITARIO_MOMENTO" integer NOT NULL,
  "COSTO_UNITARIO_MOMENTO" integer NOT NULL,
  "DESCUENTO_APLICADO" integer DEFAULT 0,
  "SUBTOTAL_ITEM" integer NOT NULL,
  "UTILIDAD_ITEM" integer NOT NULL,
  "FK_ID_PEDIDO" bigint NOT NULL,
  "FK_ID_PRODUCTO" integer NOT NULL,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_PEDIDO_HISTORIAL_ESTADO_TB" (
  "ID_HISTORIAL_ESTADO" BIGSERIAL PRIMARY KEY,
  "ESTADO_ANTERIOR" varchar(20),
  "ESTADO_NUEVO" varchar(20) NOT NULL,
  "FECHA_CAMBIO" timestamp DEFAULT CURRENT_TIMESTAMP,
  "COMENTARIO" text,
  "FK_ID_PEDIDO" bigint NOT NULL,
  "FK_ID_USUARIO" integer NOT NULL,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_FACTURA_TB" (
  "ID_FACTURA" BIGSERIAL PRIMARY KEY,
  "NUMERO_FACTURA" varchar(20) UNIQUE NOT NULL,
  "FECHA_EMISION" timestamp DEFAULT CURRENT_TIMESTAMP,
  "TOTAL_FACTURA" integer NOT NULL,
  "URL_PDF_FACTURA" varchar(500),
  "FK_ID_PEDIDO" bigint NOT NULL,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_FACTURA_DETALLE_TB" (
  "ID_FACTURA_DETALLE" BIGSERIAL PRIMARY KEY,
  "CANTIDAD" integer NOT NULL,
  "DESCRIPCION" varchar(300) NOT NULL,
  "PRECIO_UNITARIO" integer NOT NULL,
  "TOTAL_LINEA" integer NOT NULL,
  "FK_ID_FACTURA" bigint NOT NULL,
  "FK_ID_PRODUCTO" integer,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_METODO_ENVIO_TB" (
  "ID_METODO_ENVIO" SERIAL PRIMARY KEY,
  "NOMBRE_ENVIO" varchar(50) NOT NULL,
  "COSTO_BASE" integer DEFAULT 0,
  "TIEMPO_ESTIMADO_DIAS" integer DEFAULT 0,
  "ACTIVO" boolean DEFAULT true,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_METODO_PAGO_CONFIG_TB" (
  "ID_METODO_PAGO_CONFIG" SERIAL PRIMARY KEY,
  "NOMBRE" varchar(50) NOT NULL,
  "ACTIVO" boolean DEFAULT true,
  "ORDEN" integer DEFAULT 0,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);

-- ============================================================
-- PARTE 8: TESTIMONIOS, GARANTIAS, COTIZACIONES, PREMIOS Y PAGOS
-- ============================================================

CREATE TABLE IF NOT EXISTS "HOT_CLICK_TESTIMONIO_TB" (
  "ID_TESTIMONIO" SERIAL PRIMARY KEY,
  "NOMBRE_CLIENTE" varchar(100) NOT NULL,
  "CALIFICACION" integer NOT NULL CHECK ("CALIFICACION" BETWEEN 1 AND 5),
  "COMENTARIO" text NOT NULL,
  "FOTO_URL" varchar(500),
  "MOSTRAR_EN_HOME" boolean DEFAULT false,
  "FECHA_TESTIMONIO" timestamp DEFAULT CURRENT_TIMESTAMP,
  "APROBADO" boolean DEFAULT false,
  "APROBADO_POR" integer,
  "FECHA_APROBACION" timestamp,
  "FK_ID_USUARIO_FINAL" integer,
  "FK_ID_PEDIDO" bigint,
  "FK_ID_PRODUCTO" integer,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_GARANTIA_TB" (
  "ID_GARANTIA" SERIAL PRIMARY KEY,
  "NOMBRE_GARANTIA" varchar(100) NOT NULL,
  "DESCRIPCION" text,
  "DIAS_DURACION" integer NOT NULL,
  "TIPO_GARANTIA" varchar(30),
  "CONDICIONES" text,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_GARANTIA_PRODUCTO_TB" (
  "FK_ID_PRODUCTO" integer NOT NULL,
  "FK_ID_GARANTIA" integer NOT NULL,
  "FECHA_INICIO" date,
  "FECHA_FIN" date,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1,
  PRIMARY KEY ("FK_ID_PRODUCTO", "FK_ID_GARANTIA")
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_COTIZACION_ESTADO_TB" (
  "ID_ESTADO_COTIZACION" SERIAL PRIMARY KEY,
  "NOMBRE_ESTADO" varchar(30) NOT NULL,
  "DESCRIPCION" varchar(100),
  "COLOR_ESTADO" varchar(7),
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_CLIENTE_COTIZACION_TB" (
  "ID_CLIENTE" SERIAL PRIMARY KEY,
  "NOMBRE_CLIENTE" varchar(100) NOT NULL,
  "TELEFONO_WHATSAPP" varchar(20) NOT NULL,
  "TELEFONO_ALTERNO" varchar(20),
  "CORREO_ELECTRONICO" varchar(100),
  "DIRECCION" text,
  "NOTAS_CLIENTE" text,
  "FK_ID_USUARIO_SISTEMA" integer,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1,
  "FECHA_REGISTRO" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_COTIZACION_TB" (
  "ID_COTIZACION" BIGSERIAL PRIMARY KEY,
  "NUMERO_COTIZACION" varchar(20) UNIQUE NOT NULL,
  "FECHA_CREACION" timestamp DEFAULT CURRENT_TIMESTAMP,
  "FECHA_VENCIMIENTO" date NOT NULL,
  "SUBTOTAL" integer NOT NULL,
  "DESCUENTO" integer DEFAULT 0,
  "APLICA_IMPUESTO" boolean DEFAULT false,
  "PORCENTAJE_IMPUESTO" decimal(5,2) DEFAULT 13,
  "MONTO_IMPUESTO" integer DEFAULT 0,
  "TOTAL_COTIZACION" integer NOT NULL,
  "NOTAS_INTERNAS" text,
  "NOTAS_CLIENTE" text,
  "MONEDA" varchar(3) DEFAULT 'CRC',
  "FK_ID_ESTADO_COTIZACION" integer NOT NULL,
  "FK_ID_ADMIN_CREADOR" integer NOT NULL,
  "FK_ID_CLIENTE" integer,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_COTIZACION_DETALLE_TB" (
  "ID_COTIZACION_DETALLE" BIGSERIAL PRIMARY KEY,
  "CANTIDAD" integer NOT NULL DEFAULT 1,
  "PRECIO_UNITARIO_MOMENTO" integer NOT NULL,
  "DESCUENTO_PRODUCTO" integer DEFAULT 0,
  "SUBTOTAL_LINEA" integer NOT NULL,
  "OBSERVACIONES" text,
  "FK_ID_COTIZACION" bigint NOT NULL,
  "FK_ID_PRODUCTO" integer NOT NULL,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_PLANTILLA_WHATSAPP_TB" (
  "ID_PLANTILLA" SERIAL PRIMARY KEY,
  "NOMBRE_PLANTILLA" varchar(50) NOT NULL,
  "DESCRIPCION" varchar(200),
  "MENSAJE_TEMPLATE" text NOT NULL,
  "VARIABLES_DISPONIBLES" text,
  "TIPO_PLANTILLA" varchar(30),
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_WHATSAPP_ENVIO_TB" (
  "ID_ENVIO_WHATSAPP" BIGSERIAL PRIMARY KEY,
  "NUMERO_DESTINO" varchar(20) NOT NULL,
  "MENSAJE_ENVIADO" text NOT NULL,
  "URL_MEDIA_ADJUNTA" varchar(500),
  "ESTADO_ENVIO" varchar(20),
  "ERROR_MENSAJE" text,
  "FECHA_ENVIO" timestamp DEFAULT CURRENT_TIMESTAMP,
  "FECHA_LECTURA" timestamp,
  "FK_ID_COTIZACION" bigint,
  "FK_ID_PLANTILLA" integer,
  "FK_ID_ADMIN_ENVIA" integer NOT NULL,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_PREMIO_TB" (
  "ID_PREMIO" SERIAL PRIMARY KEY,
  "NOMBRE_PREMIO" varchar(100) NOT NULL,
  "DESCRIPCION" text,
  "TIPO_PREMIO" varchar(30) NOT NULL,
  "VALOR_PREMIO" integer DEFAULT 0,
  "FK_ID_PRODUCTO_PREMIO" integer,
  "PROBABILIDAD" decimal(5,2) NOT NULL,
  "STOCK_DISPONIBLE" integer DEFAULT -1,
  "COLOR_RULETA" varchar(7) NOT NULL,
  "ICONO_URL" varchar(500),
  "ACTIVO" boolean DEFAULT true,
  "FECHA_INICIO" timestamp,
  "FECHA_FIN" timestamp,
  "FK_ID_ADMIN_CLIENTE" integer NOT NULL,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_GIRO_RULETA_TB" (
  "ID_GIRO" BIGSERIAL PRIMARY KEY,
  "TIPO_ORIGEN" varchar(30) NOT NULL,
  "USADO" boolean DEFAULT false,
  "FECHA_ASIGNACION" timestamp DEFAULT CURRENT_TIMESTAMP,
  "FECHA_USO" timestamp,
  "FK_ID_USUARIO_FINAL" integer NOT NULL,
  "FK_ID_PEDIDO" bigint,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_RESULTADO_RULETA_TB" (
  "ID_RESULTADO" BIGSERIAL PRIMARY KEY,
  "FECHA_GIRO" timestamp DEFAULT CURRENT_TIMESTAMP,
  "CODIGO_CANJE" varchar(20) UNIQUE,
  "CANJEADO" boolean DEFAULT false,
  "FECHA_CANJE" timestamp,
  "EXPIRA_EN" timestamp,
  "FK_ID_GIRO" bigint NOT NULL UNIQUE,
  "FK_ID_USUARIO_FINAL" integer NOT NULL,
  "FK_ID_PREMIO" integer NOT NULL,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_REFERIDO_TB" (
  "ID_REFERIDO" SERIAL PRIMARY KEY,
  "CODIGO_REFERIDO" varchar(20) UNIQUE NOT NULL,
  "TOTAL_REFERIDOS" integer DEFAULT 0,
  "GIROS_GANADOS" integer DEFAULT 0,
  "FECHA_CREACION" timestamp DEFAULT CURRENT_TIMESTAMP,
  "FK_ID_USUARIO_REFERIDOR" integer NOT NULL,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_REFERIDO_DETALLE_TB" (
  "ID_REFERIDO_DETALLE" SERIAL PRIMARY KEY,
  "FECHA_REGISTRO" timestamp DEFAULT CURRENT_TIMESTAMP,
  "GIRO_OTORGADO" boolean DEFAULT false,
  "FK_ID_REFERIDO" integer NOT NULL,
  "FK_ID_USUARIO_NUEVO" integer NOT NULL,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "hot_click_pago_tb" (
  "id_pago"             BIGSERIAL    PRIMARY KEY,
  "merchant_token"      varchar(500) UNIQUE NOT NULL,
  "redirect_url"        varchar(1000),
  "monto"               integer      NOT NULL,
  "moneda"              varchar(3)   NOT NULL DEFAULT 'CRC',
  "estado_pago"         varchar(30)  NOT NULL DEFAULT 'PENDIENTE',
  "metodo_pago_tipo"    varchar(30),
  "fecha_creacion"      timestamp    DEFAULT CURRENT_TIMESTAMP,
  "fecha_actualizacion" timestamp    DEFAULT CURRENT_TIMESTAMP,
  "fecha_expiracion"    timestamp,
  "fk_id_pedido"        bigint       NOT NULL,
  "fk_id_usuario"       integer      NOT NULL,
  "fk_id_estado"        integer      NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "hot_click_transaccion_pago_tb" (
  "id_transaccion"      BIGSERIAL    PRIMARY KEY,
  "payxpert_txn_id"     varchar(200),
  "error_code"          varchar(10)  NOT NULL,
  "error_message"       varchar(500),
  "card_last4"          varchar(4),
  "card_brand"          varchar(20),
  "tipo_operacion"      varchar(30)  NOT NULL,
  "monto_operacion"     integer      NOT NULL,
  "payload_respuesta"   jsonb,
  "fecha_transaccion"   timestamp    DEFAULT CURRENT_TIMESTAMP,
  "fk_id_pago"          bigint       NOT NULL,
  "fk_id_estado"        integer      NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "hot_click_webhook_event_tb" (
  "id_webhook_event"    BIGSERIAL    PRIMARY KEY,
  "merchant_token"      varchar(500) NOT NULL,
  "evento_tipo"         varchar(50)  NOT NULL,
  "payload_raw"         jsonb        NOT NULL,
  "procesado"           boolean      DEFAULT false,
  "procesado_en"        timestamp,
  "error_procesamiento" text,
  "ip_origen"           varchar(45),
  "fecha_recepcion"     timestamp    DEFAULT CURRENT_TIMESTAMP,
  "fk_id_estado"        integer      NOT NULL DEFAULT 1,
  UNIQUE ("merchant_token", "evento_tipo")
);

CREATE TABLE IF NOT EXISTS "hot_click_payment_log_tb" (
  "id_log"              BIGSERIAL    PRIMARY KEY,
  "accion"              varchar(50)  NOT NULL,
  "url_llamada"         varchar(500) NOT NULL,
  "http_method"         varchar(10)  NOT NULL,
  "request_body"        jsonb,
  "response_code"       integer,
  "response_body"       jsonb,
  "duracion_ms"         integer,
  "exitoso"             boolean      DEFAULT false,
  "fecha_log"           timestamp    DEFAULT CURRENT_TIMESTAMP,
  "fk_id_pago"          bigint,
  "fk_id_usuario"       integer,
  "fk_id_estado"        integer      NOT NULL DEFAULT 1
);


-- ============================================================
-- PARTE 9: FINANZAS Y AUDITORIA
-- ============================================================

CREATE TABLE IF NOT EXISTS "HOT_CLICK_FINANZA_PRODUCTO_TB" (
  "ID_FINANZA_PRODUCTO" BIGSERIAL PRIMARY KEY,
  "FECHA_CALCULO" date NOT NULL,
  "UNIDADES_VENDIDAS" integer DEFAULT 0,
  "INGRESOS_BRUTOS" integer DEFAULT 0,
  "COSTO_MERCADERIA" integer DEFAULT 0,
  "UTILIDAD_BRUTA" integer DEFAULT 0,
  "MARGEN_BRUTO" decimal(8,2),
  "FK_ID_PRODUCTO" integer NOT NULL,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_FINANZA_GLOBAL_TB" (
  "ID_FINANZA_GLOBAL" BIGSERIAL PRIMARY KEY,
  "FECHA_CALCULO" date NOT NULL UNIQUE,
  "TOTAL_VENTAS" integer DEFAULT 0,
  "TOTAL_COSTOS" integer DEFAULT 0,
  "UTILIDAD_NETA" integer DEFAULT 0,
  "GASTOS_OPERATIVOS" integer DEFAULT 0,
  "PEDIDOS_COMPLETADOS" integer DEFAULT 0,
  "PEDIDOS_CANCELADOS" integer DEFAULT 0,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_GASTO_OPERATIVO_TB" (
  "ID_GASTO" SERIAL PRIMARY KEY,
  "DESCRIPCION" varchar(200) NOT NULL,
  "MONTO" integer NOT NULL,
  "TIPO_GASTO" varchar(50),
  "FECHA_GASTO" date NOT NULL,
  "COMPROBANTE_URL" varchar(500),
  "FK_ID_ADMIN_CLIENTE" integer NOT NULL,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_METRICA_VENTA_TB" (
  "ID_METRICA" BIGSERIAL PRIMARY KEY,
  "FECHA_METRICA" date NOT NULL,
  "PEDIDOS_NUEVOS" integer DEFAULT 0,
  "INGRESOS_DIA" integer DEFAULT 0,
  "TICKET_PROMEDIO" integer DEFAULT 0,
  "PRODUCTOS_AGOTADOS" integer DEFAULT 0,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_DASHBOARD_KPI_TB" (
  "ID_KPI" BIGSERIAL PRIMARY KEY,
  "FECHA_KPI" date NOT NULL,
  "VENTAS_DIA" integer DEFAULT 0,
  "VENTAS_MES" integer DEFAULT 0,
  "CLIENTES_NUEVOS" integer DEFAULT 0,
  "PRODUCTOS_BAJO_STOCK" integer DEFAULT 0,
  "COTIZACIONES_PENDIENTES" integer DEFAULT 0,
  "GIROS_PENDIENTES" integer DEFAULT 0,
  "FK_ID_ADMIN_CLIENTE" integer NOT NULL,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_PRODUCTO_METRICA_TB" (
  "ID_PRODUCTO_METRICA" BIGSERIAL PRIMARY KEY,
  "FECHA_METRICA" date NOT NULL,
  "VISTAS" integer DEFAULT 0,
  "VECES_EN_CARRITO" integer DEFAULT 0,
  "VECES_VENDIDO" integer DEFAULT 0,
  "VECES_COTIZADO" integer DEFAULT 0,
  "FK_ID_PRODUCTO" integer NOT NULL,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_AUDITORIA_TB" (
  "ID_AUDITORIA" BIGSERIAL PRIMARY KEY,
  "TABLA_AFECTADA" varchar(100) NOT NULL,
  "OPERACION" varchar(10) NOT NULL,
  "DATO_ANTERIOR" jsonb,
  "DATO_NUEVO" jsonb,
  "FECHA_OPERACION" timestamp DEFAULT CURRENT_TIMESTAMP,
  "IP_ORIGEN" varchar(45),
  "FK_ID_USUARIO" integer,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_LOG_ERROR_TB" (
  "ID_ERROR" BIGSERIAL PRIMARY KEY,
  "TIPO_ERROR" varchar(50),
  "MENSAJE_ERROR" text,
  "STACK_TRACE" text,
  "ENDPOINT" varchar(200),
  "FECHA_ERROR" timestamp DEFAULT CURRENT_TIMESTAMP,
  "FK_ID_USUARIO" integer,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_LOG_CONEXION_TB" (
  "ID_CONEXION" BIGSERIAL PRIMARY KEY,
  "ACCION" varchar(20) NOT NULL,
  "IP_ADDRESS" varchar(45),
  "EXITOSO" boolean DEFAULT false,
  "FECHA_INTENTO" timestamp DEFAULT CURRENT_TIMESTAMP,
  "FK_ID_USUARIO" integer,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_ALERTA_TB" (
  "ID_ALERTA" BIGSERIAL PRIMARY KEY,
  "TIPO_ALERTA" varchar(50) NOT NULL,
  "MENSAJE" text NOT NULL,
  "LEIDA" boolean DEFAULT false,
  "FECHA_ALERTA" timestamp DEFAULT CURRENT_TIMESTAMP,
  "FK_ID_ADMIN_CLIENTE" integer NOT NULL,
  "FK_ID_USUARIO_LECTOR" integer,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_IMPUESTO_EXENTO_PRODUCTO_TB" (
  "ID_EXENTO" SERIAL PRIMARY KEY,
  "FK_ID_PRODUCTO" integer NOT NULL,
  "FK_ID_ADMIN_CLIENTE" integer NOT NULL,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "HOT_CLICK_CATEGORIA_EXENTA_TB" (
  "ID_CATEGORIA_EXENTA" SERIAL PRIMARY KEY,
  "FK_ID_CATEGORIA" integer NOT NULL,
  "FK_ID_ADMIN_CLIENTE" integer NOT NULL,
  "FK_ID_ESTADO" integer NOT NULL DEFAULT 1
);


-- ============================================================
-- PARTE 10: FOREIGN KEYS, INDICES, TRIGGERS, FUNCIONES, VISTAS Y DATOS
-- ============================================================

-- FOREIGN KEYS - Usuarios
ALTER TABLE "HOT_CLICK_USUARIO_TB" ADD FOREIGN KEY ("FK_ID_ESTADO") REFERENCES "HOT_CLICK_ESTADO_TB" ("ID_ESTADO");
ALTER TABLE "HOT_CLICK_ROL_TB" ADD FOREIGN KEY ("FK_ID_ESTADO") REFERENCES "HOT_CLICK_ESTADO_TB" ("ID_ESTADO");
ALTER TABLE "HOT_CLICK_USUARIO_ROL_TB" ADD FOREIGN KEY ("FK_ID_USUARIO") REFERENCES "HOT_CLICK_USUARIO_TB" ("ID_USUARIO");
ALTER TABLE "HOT_CLICK_USUARIO_ROL_TB" ADD FOREIGN KEY ("FK_ID_ROL") REFERENCES "HOT_CLICK_ROL_TB" ("ID_ROL");
ALTER TABLE "HOT_CLICK_USUARIO_ROL_TB" ADD FOREIGN KEY ("FK_ID_ESTADO") REFERENCES "HOT_CLICK_ESTADO_TB" ("ID_ESTADO");
ALTER TABLE "HOT_CLICK_PERMISO_TB" ADD FOREIGN KEY ("FK_ID_ESTADO") REFERENCES "HOT_CLICK_ESTADO_TB" ("ID_ESTADO");
ALTER TABLE "HOT_CLICK_ROL_PERMISO_TB" ADD FOREIGN KEY ("FK_ID_ROL") REFERENCES "HOT_CLICK_ROL_TB" ("ID_ROL");
ALTER TABLE "HOT_CLICK_ROL_PERMISO_TB" ADD FOREIGN KEY ("FK_ID_PERMISO") REFERENCES "HOT_CLICK_PERMISO_TB" ("ID_PERMISO");
ALTER TABLE "HOT_CLICK_ROL_PERMISO_TB" ADD FOREIGN KEY ("FK_ID_ESTADO") REFERENCES "HOT_CLICK_ESTADO_TB" ("ID_ESTADO");
ALTER TABLE "HOT_CLICK_SESION_TB" ADD FOREIGN KEY ("FK_ID_USUARIO") REFERENCES "HOT_CLICK_USUARIO_TB" ("ID_USUARIO");
ALTER TABLE "HOT_CLICK_SESION_TB" ADD FOREIGN KEY ("FK_ID_ESTADO") REFERENCES "HOT_CLICK_ESTADO_TB" ("ID_ESTADO");
ALTER TABLE "HOT_CLICK_CODIGO_OTP_TB" ADD FOREIGN KEY ("FK_ID_USUARIO") REFERENCES "HOT_CLICK_USUARIO_TB" ("ID_USUARIO");
ALTER TABLE "HOT_CLICK_CODIGO_OTP_TB" ADD FOREIGN KEY ("FK_ID_TIPO_OTP") REFERENCES "HOT_CLICK_TIPO_OTP_TB" ("ID_TIPO_OTP");
ALTER TABLE "HOT_CLICK_CODIGO_OTP_TB" ADD FOREIGN KEY ("FK_ID_ESTADO") REFERENCES "HOT_CLICK_ESTADO_TB" ("ID_ESTADO");
ALTER TABLE "HOT_CLICK_USUARIO_DIRECCION_TB" ADD FOREIGN KEY ("FK_ID_USUARIO") REFERENCES "HOT_CLICK_USUARIO_TB" ("ID_USUARIO");
ALTER TABLE "HOT_CLICK_USUARIO_DIRECCION_TB" ADD FOREIGN KEY ("FK_ID_DISTRITO") REFERENCES "HOT_CLICK_DISTRITO_TB" ("ID_DISTRITO");
ALTER TABLE "HOT_CLICK_USUARIO_DIRECCION_TB" ADD FOREIGN KEY ("FK_ID_ESTADO") REFERENCES "HOT_CLICK_ESTADO_TB" ("ID_ESTADO");

-- FOREIGN KEYS - Configuracion
ALTER TABLE "HOT_CLICK_CONFIGURACION_MONEDA_TB" ADD FOREIGN KEY ("FK_ID_ADMIN_CLIENTE") REFERENCES "HOT_CLICK_USUARIO_TB" ("ID_USUARIO");
ALTER TABLE "HOT_CLICK_CONFIGURACION_MONEDA_TB" ADD FOREIGN KEY ("FK_ID_ESTADO") REFERENCES "HOT_CLICK_ESTADO_TB" ("ID_ESTADO");
ALTER TABLE "HOT_CLICK_CONFIGURACION_IMPUESTO_TB" ADD FOREIGN KEY ("FK_ID_ADMIN_CLIENTE") REFERENCES "HOT_CLICK_USUARIO_TB" ("ID_USUARIO");
ALTER TABLE "HOT_CLICK_CONFIGURACION_IMPUESTO_TB" ADD FOREIGN KEY ("FK_ID_ESTADO") REFERENCES "HOT_CLICK_ESTADO_TB" ("ID_ESTADO");
ALTER TABLE "HOT_CLICK_RANGO_PRECIO_TB" ADD FOREIGN KEY ("FK_ID_ESTADO") REFERENCES "HOT_CLICK_ESTADO_TB" ("ID_ESTADO");

-- FOREIGN KEYS - Ubicaciones
ALTER TABLE "HOT_CLICK_PAIS_TB" ADD FOREIGN KEY ("FK_ID_ESTADO") REFERENCES "HOT_CLICK_ESTADO_TB" ("ID_ESTADO");
ALTER TABLE "HOT_CLICK_PROVINCIA_TB" ADD FOREIGN KEY ("FK_ID_PAIS") REFERENCES "HOT_CLICK_PAIS_TB" ("ID_PAIS");
ALTER TABLE "HOT_CLICK_PROVINCIA_TB" ADD FOREIGN KEY ("FK_ID_ESTADO") REFERENCES "HOT_CLICK_ESTADO_TB" ("ID_ESTADO");
ALTER TABLE "HOT_CLICK_CANTON_TB" ADD FOREIGN KEY ("FK_ID_PROVINCIA") REFERENCES "HOT_CLICK_PROVINCIA_TB" ("ID_PROVINCIA");
ALTER TABLE "HOT_CLICK_CANTON_TB" ADD FOREIGN KEY ("FK_ID_ESTADO") REFERENCES "HOT_CLICK_ESTADO_TB" ("ID_ESTADO");
ALTER TABLE "HOT_CLICK_DISTRITO_TB" ADD FOREIGN KEY ("FK_ID_CANTON") REFERENCES "HOT_CLICK_CANTON_TB" ("ID_CANTON");
ALTER TABLE "HOT_CLICK_DISTRITO_TB" ADD FOREIGN KEY ("FK_ID_ESTADO") REFERENCES "HOT_CLICK_ESTADO_TB" ("ID_ESTADO");
ALTER TABLE "HOT_CLICK_BARRIO_TB" ADD FOREIGN KEY ("FK_ID_DISTRITO") REFERENCES "HOT_CLICK_DISTRITO_TB" ("ID_DISTRITO");
ALTER TABLE "HOT_CLICK_BARRIO_TB" ADD FOREIGN KEY ("FK_ID_ESTADO") REFERENCES "HOT_CLICK_ESTADO_TB" ("ID_ESTADO");
ALTER TABLE "HOT_CLICK_COORDENADA_UBICACION_TB" ADD FOREIGN KEY ("FK_ID_ESTADO") REFERENCES "HOT_CLICK_ESTADO_TB" ("ID_ESTADO");

-- FOREIGN KEYS - Bodegas
ALTER TABLE "HOT_CLICK_BODEGA_TB" ADD FOREIGN KEY ("FK_ID_ADMIN_CLIENTE") REFERENCES "HOT_CLICK_USUARIO_TB" ("ID_USUARIO");
ALTER TABLE "HOT_CLICK_BODEGA_TB" ADD FOREIGN KEY ("FK_ID_ESTADO") REFERENCES "HOT_CLICK_ESTADO_TB" ("ID_ESTADO");
ALTER TABLE "HOT_CLICK_BODEGA_UBICACION_TB" ADD FOREIGN KEY ("FK_ID_BODEGA") REFERENCES "HOT_CLICK_BODEGA_TB" ("ID_BODEGA");
ALTER TABLE "HOT_CLICK_BODEGA_UBICACION_TB" ADD FOREIGN KEY ("FK_ID_DISTRITO") REFERENCES "HOT_CLICK_DISTRITO_TB" ("ID_DISTRITO");
ALTER TABLE "HOT_CLICK_BODEGA_UBICACION_TB" ADD FOREIGN KEY ("FK_ID_BARRIO") REFERENCES "HOT_CLICK_BARRIO_TB" ("ID_BARRIO");
ALTER TABLE "HOT_CLICK_BODEGA_UBICACION_TB" ADD FOREIGN KEY ("FK_ID_ESTADO") REFERENCES "HOT_CLICK_ESTADO_TB" ("ID_ESTADO");
ALTER TABLE "HOT_CLICK_BODEGA_USUARIO_TB" ADD FOREIGN KEY ("FK_ID_BODEGA") REFERENCES "HOT_CLICK_BODEGA_TB" ("ID_BODEGA");
ALTER TABLE "HOT_CLICK_BODEGA_USUARIO_TB" ADD FOREIGN KEY ("FK_ID_USUARIO") REFERENCES "HOT_CLICK_USUARIO_TB" ("ID_USUARIO");
ALTER TABLE "HOT_CLICK_BODEGA_USUARIO_TB" ADD FOREIGN KEY ("FK_ID_ESTADO") REFERENCES "HOT_CLICK_ESTADO_TB" ("ID_ESTADO");
ALTER TABLE "HOT_CLICK_BODEGA_HISTORIAL_TB" ADD FOREIGN KEY ("FK_ID_BODEGA") REFERENCES "HOT_CLICK_BODEGA_TB" ("ID_BODEGA");
ALTER TABLE "HOT_CLICK_BODEGA_HISTORIAL_TB" ADD FOREIGN KEY ("FK_ID_USUARIO") REFERENCES "HOT_CLICK_USUARIO_TB" ("ID_USUARIO");
ALTER TABLE "HOT_CLICK_BODEGA_HISTORIAL_TB" ADD FOREIGN KEY ("FK_ID_ESTADO") REFERENCES "HOT_CLICK_ESTADO_TB" ("ID_ESTADO");

-- FOREIGN KEYS - Categorias
ALTER TABLE "HOT_CLICK_CATEGORIA_TB" ADD FOREIGN KEY ("FK_ID_CATEGORIA_PADRE") REFERENCES "HOT_CLICK_CATEGORIA_TB" ("ID_CATEGORIA");
ALTER TABLE "HOT_CLICK_CATEGORIA_TB" ADD FOREIGN KEY ("FK_ID_ADMIN_CLIENTE") REFERENCES "HOT_CLICK_USUARIO_TB" ("ID_USUARIO");
ALTER TABLE "HOT_CLICK_CATEGORIA_TB" ADD FOREIGN KEY ("FK_ID_ESTADO") REFERENCES "HOT_CLICK_ESTADO_TB" ("ID_ESTADO");
ALTER TABLE "HOT_CLICK_ETIQUETA_TB" ADD FOREIGN KEY ("FK_ID_ESTADO") REFERENCES "HOT_CLICK_ESTADO_TB" ("ID_ESTADO");
ALTER TABLE "HOT_CLICK_PRODUCTO_ETIQUETA_TB" ADD FOREIGN KEY ("FK_ID_PRODUCTO") REFERENCES "HOT_CLICK_PRODUCTO_TB" ("ID_PRODUCTO") ON DELETE CASCADE;
ALTER TABLE "HOT_CLICK_PRODUCTO_ETIQUETA_TB" ADD FOREIGN KEY ("FK_ID_ETIQUETA") REFERENCES "HOT_CLICK_ETIQUETA_TB" ("ID_ETIQUETA");
ALTER TABLE "HOT_CLICK_PRODUCTO_ETIQUETA_TB" ADD FOREIGN KEY ("FK_ID_ESTADO") REFERENCES "HOT_CLICK_ESTADO_TB" ("ID_ESTADO");
ALTER TABLE "HOT_CLICK_CATEGORIA_ETIQUETA_TB" ADD FOREIGN KEY ("FK_ID_CATEGORIA") REFERENCES "HOT_CLICK_CATEGORIA_TB" ("ID_CATEGORIA");
ALTER TABLE "HOT_CLICK_CATEGORIA_ETIQUETA_TB" ADD FOREIGN KEY ("FK_ID_ETIQUETA") REFERENCES "HOT_CLICK_ETIQUETA_TB" ("ID_ETIQUETA");
ALTER TABLE "HOT_CLICK_CATEGORIA_ETIQUETA_TB" ADD FOREIGN KEY ("FK_ID_ESTADO") REFERENCES "HOT_CLICK_ESTADO_TB" ("ID_ESTADO");
ALTER TABLE "HOT_CLICK_MARCA_TB" ADD FOREIGN KEY ("FK_ID_ADMIN_CLIENTE") REFERENCES "HOT_CLICK_USUARIO_TB" ("ID_USUARIO");
ALTER TABLE "HOT_CLICK_MARCA_TB" ADD FOREIGN KEY ("FK_ID_ESTADO") REFERENCES "HOT_CLICK_ESTADO_TB" ("ID_ESTADO");

-- FOREIGN KEYS - Productos
ALTER TABLE "HOT_CLICK_PRODUCTO_TB" ADD FOREIGN KEY ("FK_ID_BODEGA") REFERENCES "HOT_CLICK_BODEGA_TB" ("ID_BODEGA");
ALTER TABLE "HOT_CLICK_PRODUCTO_TB" ADD FOREIGN KEY ("FK_ID_CATEGORIA") REFERENCES "HOT_CLICK_CATEGORIA_TB" ("ID_CATEGORIA");
ALTER TABLE "HOT_CLICK_PRODUCTO_TB" ADD FOREIGN KEY ("FK_ID_MARCA") REFERENCES "HOT_CLICK_MARCA_TB" ("ID_MARCA");
ALTER TABLE "HOT_CLICK_PRODUCTO_TB" ADD FOREIGN KEY ("FK_ID_ADMIN_CLIENTE") REFERENCES "HOT_CLICK_USUARIO_TB" ("ID_USUARIO");
ALTER TABLE "HOT_CLICK_PRODUCTO_TB" ADD FOREIGN KEY ("FK_ID_ESTADO") REFERENCES "HOT_CLICK_ESTADO_TB" ("ID_ESTADO");
ALTER TABLE "HOT_CLICK_PRODUCTO_IMAGEN_TB" ADD FOREIGN KEY ("FK_ID_PRODUCTO") REFERENCES "HOT_CLICK_PRODUCTO_TB" ("ID_PRODUCTO") ON DELETE CASCADE;
ALTER TABLE "HOT_CLICK_PRODUCTO_IMAGEN_TB" ADD FOREIGN KEY ("FK_ID_ESTADO") REFERENCES "HOT_CLICK_ESTADO_TB" ("ID_ESTADO");
ALTER TABLE "HOT_CLICK_PRODUCTO_VIDEO_TB" ADD FOREIGN KEY ("FK_ID_PRODUCTO") REFERENCES "HOT_CLICK_PRODUCTO_TB" ("ID_PRODUCTO") ON DELETE CASCADE;
ALTER TABLE "HOT_CLICK_PRODUCTO_VIDEO_TB" ADD FOREIGN KEY ("FK_ID_ESTADO") REFERENCES "HOT_CLICK_ESTADO_TB" ("ID_ESTADO");
ALTER TABLE "HOT_CLICK_PRODUCTO_ATRIBUTO_TB" ADD FOREIGN KEY ("FK_ID_ESTADO") REFERENCES "HOT_CLICK_ESTADO_TB" ("ID_ESTADO");
ALTER TABLE "HOT_CLICK_PRODUCTO_ATRIBUTO_VALOR_TB" ADD FOREIGN KEY ("FK_ID_ATRIBUTO") REFERENCES "HOT_CLICK_PRODUCTO_ATRIBUTO_TB" ("ID_ATRIBUTO");
ALTER TABLE "HOT_CLICK_PRODUCTO_ATRIBUTO_VALOR_TB" ADD FOREIGN KEY ("FK_ID_ESTADO") REFERENCES "HOT_CLICK_ESTADO_TB" ("ID_ESTADO");
ALTER TABLE "HOT_CLICK_PRODUCTO_ATRIBUTO_ASIGNACION_TB" ADD FOREIGN KEY ("FK_ID_PRODUCTO") REFERENCES "HOT_CLICK_PRODUCTO_TB" ("ID_PRODUCTO") ON DELETE CASCADE;
ALTER TABLE "HOT_CLICK_PRODUCTO_ATRIBUTO_ASIGNACION_TB" ADD FOREIGN KEY ("FK_ID_VALOR_ATRIBUTO") REFERENCES "HOT_CLICK_PRODUCTO_ATRIBUTO_VALOR_TB" ("ID_VALOR_ATRIBUTO");
ALTER TABLE "HOT_CLICK_PRODUCTO_ATRIBUTO_ASIGNACION_TB" ADD FOREIGN KEY ("FK_ID_ESTADO") REFERENCES "HOT_CLICK_ESTADO_TB" ("ID_ESTADO");
ALTER TABLE "HOT_CLICK_PRODUCTO_VARIANTE_TB" ADD FOREIGN KEY ("FK_ID_PRODUCTO") REFERENCES "HOT_CLICK_PRODUCTO_TB" ("ID_PRODUCTO") ON DELETE CASCADE;
ALTER TABLE "HOT_CLICK_PRODUCTO_VARIANTE_TB" ADD FOREIGN KEY ("FK_ID_ESTADO") REFERENCES "HOT_CLICK_ESTADO_TB" ("ID_ESTADO");
ALTER TABLE "HOT_CLICK_PRODUCTO_VARIANTE_ATRIBUTO_TB" ADD FOREIGN KEY ("FK_ID_VARIANTE") REFERENCES "HOT_CLICK_PRODUCTO_VARIANTE_TB" ("ID_VARIANTE") ON DELETE CASCADE;
ALTER TABLE "HOT_CLICK_PRODUCTO_VARIANTE_ATRIBUTO_TB" ADD FOREIGN KEY ("FK_ID_VALOR_ATRIBUTO") REFERENCES "HOT_CLICK_PRODUCTO_ATRIBUTO_VALOR_TB" ("ID_VALOR_ATRIBUTO");

-- FOREIGN KEYS - Carrito
ALTER TABLE "HOT_CLICK_CARRITO_TB" ADD FOREIGN KEY ("FK_ID_USUARIO_FINAL") REFERENCES "HOT_CLICK_USUARIO_TB" ("ID_USUARIO");
ALTER TABLE "HOT_CLICK_CARRITO_TB" ADD FOREIGN KEY ("FK_ID_ESTADO") REFERENCES "HOT_CLICK_ESTADO_TB" ("ID_ESTADO");
ALTER TABLE "HOT_CLICK_CARRITO_ITEM_TB" ADD FOREIGN KEY ("FK_ID_CARRITO") REFERENCES "HOT_CLICK_CARRITO_TB" ("ID_CARRITO") ON DELETE CASCADE;
ALTER TABLE "HOT_CLICK_CARRITO_ITEM_TB" ADD FOREIGN KEY ("FK_ID_PRODUCTO") REFERENCES "HOT_CLICK_PRODUCTO_TB" ("ID_PRODUCTO");
ALTER TABLE "HOT_CLICK_CARRITO_ITEM_TB" ADD FOREIGN KEY ("FK_ID_ESTADO") REFERENCES "HOT_CLICK_ESTADO_TB" ("ID_ESTADO");
ALTER TABLE "HOT_CLICK_CARRITO_DESCUENTO_TB" ADD FOREIGN KEY ("FK_ID_CARRITO") REFERENCES "HOT_CLICK_CARRITO_TB" ("ID_CARRITO") ON DELETE CASCADE;
ALTER TABLE "HOT_CLICK_CARRITO_DESCUENTO_TB" ADD FOREIGN KEY ("FK_ID_ESTADO") REFERENCES "HOT_CLICK_ESTADO_TB" ("ID_ESTADO");

-- FOREIGN KEYS - Pedidos
ALTER TABLE "HOT_CLICK_PEDIDO_TB" ADD FOREIGN KEY ("FK_ID_USUARIO_FINAL") REFERENCES "HOT_CLICK_USUARIO_TB" ("ID_USUARIO");
ALTER TABLE "HOT_CLICK_PEDIDO_TB" ADD FOREIGN KEY ("FK_ID_BODEGA") REFERENCES "HOT_CLICK_BODEGA_TB" ("ID_BODEGA");
ALTER TABLE "HOT_CLICK_PEDIDO_TB" ADD FOREIGN KEY ("FK_ID_ESTADO") REFERENCES "HOT_CLICK_ESTADO_TB" ("ID_ESTADO");
ALTER TABLE "HOT_CLICK_PEDIDO_ITEM_TB" ADD FOREIGN KEY ("FK_ID_PEDIDO") REFERENCES "HOT_CLICK_PEDIDO_TB" ("ID_PEDIDO") ON DELETE CASCADE;
ALTER TABLE "HOT_CLICK_PEDIDO_ITEM_TB" ADD FOREIGN KEY ("FK_ID_PRODUCTO") REFERENCES "HOT_CLICK_PRODUCTO_TB" ("ID_PRODUCTO");
ALTER TABLE "HOT_CLICK_PEDIDO_ITEM_TB" ADD FOREIGN KEY ("FK_ID_ESTADO") REFERENCES "HOT_CLICK_ESTADO_TB" ("ID_ESTADO");
ALTER TABLE "HOT_CLICK_PEDIDO_HISTORIAL_ESTADO_TB" ADD FOREIGN KEY ("FK_ID_PEDIDO") REFERENCES "HOT_CLICK_PEDIDO_TB" ("ID_PEDIDO") ON DELETE CASCADE;
ALTER TABLE "HOT_CLICK_PEDIDO_HISTORIAL_ESTADO_TB" ADD FOREIGN KEY ("FK_ID_USUARIO") REFERENCES "HOT_CLICK_USUARIO_TB" ("ID_USUARIO");
ALTER TABLE "HOT_CLICK_FACTURA_TB" ADD FOREIGN KEY ("FK_ID_PEDIDO") REFERENCES "HOT_CLICK_PEDIDO_TB" ("ID_PEDIDO");
ALTER TABLE "HOT_CLICK_FACTURA_DETALLE_TB" ADD FOREIGN KEY ("FK_ID_FACTURA") REFERENCES "HOT_CLICK_FACTURA_TB" ("ID_FACTURA") ON DELETE CASCADE;
ALTER TABLE "HOT_CLICK_METODO_ENVIO_TB" ADD FOREIGN KEY ("FK_ID_ESTADO") REFERENCES "HOT_CLICK_ESTADO_TB" ("ID_ESTADO");
ALTER TABLE "HOT_CLICK_METODO_PAGO_CONFIG_TB" ADD FOREIGN KEY ("FK_ID_ESTADO") REFERENCES "HOT_CLICK_ESTADO_TB" ("ID_ESTADO");

-- FOREIGN KEYS - Testimonios
ALTER TABLE "HOT_CLICK_TESTIMONIO_TB" ADD FOREIGN KEY ("FK_ID_USUARIO_FINAL") REFERENCES "HOT_CLICK_USUARIO_TB" ("ID_USUARIO");
ALTER TABLE "HOT_CLICK_TESTIMONIO_TB" ADD FOREIGN KEY ("FK_ID_PEDIDO") REFERENCES "HOT_CLICK_PEDIDO_TB" ("ID_PEDIDO");
ALTER TABLE "HOT_CLICK_TESTIMONIO_TB" ADD FOREIGN KEY ("FK_ID_PRODUCTO") REFERENCES "HOT_CLICK_PRODUCTO_TB" ("ID_PRODUCTO");
ALTER TABLE "HOT_CLICK_TESTIMONIO_TB" ADD FOREIGN KEY ("APROBADO_POR") REFERENCES "HOT_CLICK_USUARIO_TB" ("ID_USUARIO");
ALTER TABLE "HOT_CLICK_GARANTIA_TB" ADD FOREIGN KEY ("FK_ID_ESTADO") REFERENCES "HOT_CLICK_ESTADO_TB" ("ID_ESTADO");
ALTER TABLE "HOT_CLICK_GARANTIA_PRODUCTO_TB" ADD FOREIGN KEY ("FK_ID_PRODUCTO") REFERENCES "HOT_CLICK_PRODUCTO_TB" ("ID_PRODUCTO");
ALTER TABLE "HOT_CLICK_GARANTIA_PRODUCTO_TB" ADD FOREIGN KEY ("FK_ID_GARANTIA") REFERENCES "HOT_CLICK_GARANTIA_TB" ("ID_GARANTIA");

-- FOREIGN KEYS - Pagos PayXpert
ALTER TABLE "hot_click_pago_tb" ADD FOREIGN KEY ("fk_id_pedido") REFERENCES "HOT_CLICK_PEDIDO_TB" ("ID_PEDIDO");
ALTER TABLE "hot_click_pago_tb" ADD FOREIGN KEY ("fk_id_usuario") REFERENCES "HOT_CLICK_USUARIO_TB" ("ID_USUARIO");
ALTER TABLE "hot_click_pago_tb" ADD FOREIGN KEY ("fk_id_estado") REFERENCES "HOT_CLICK_ESTADO_TB" ("ID_ESTADO");
ALTER TABLE "hot_click_transaccion_pago_tb" ADD FOREIGN KEY ("fk_id_pago") REFERENCES "hot_click_pago_tb" ("id_pago") ON DELETE CASCADE;
ALTER TABLE "hot_click_transaccion_pago_tb" ADD FOREIGN KEY ("fk_id_estado") REFERENCES "HOT_CLICK_ESTADO_TB" ("ID_ESTADO");
ALTER TABLE "hot_click_webhook_event_tb" ADD FOREIGN KEY ("fk_id_estado") REFERENCES "HOT_CLICK_ESTADO_TB" ("ID_ESTADO");
ALTER TABLE "hot_click_payment_log_tb" ADD FOREIGN KEY ("fk_id_pago") REFERENCES "hot_click_pago_tb" ("id_pago");
ALTER TABLE "hot_click_payment_log_tb" ADD FOREIGN KEY ("fk_id_usuario") REFERENCES "HOT_CLICK_USUARIO_TB" ("ID_USUARIO");

-- ============================================================
-- INDICES
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_producto_categoria ON "HOT_CLICK_PRODUCTO_TB" ("FK_ID_CATEGORIA");
CREATE INDEX IF NOT EXISTS idx_producto_unico ON "HOT_CLICK_PRODUCTO_TB" ("ES_UNICO", "VENDIDO");
CREATE INDEX IF NOT EXISTS idx_pedido_usuario ON "HOT_CLICK_PEDIDO_TB" ("FK_ID_USUARIO_FINAL");
CREATE INDEX IF NOT EXISTS idx_pedido_fecha ON "HOT_CLICK_PEDIDO_TB" ("FECHA_PEDIDO");
CREATE INDEX IF NOT EXISTS idx_giro_usuario ON "HOT_CLICK_GIRO_RULETA_TB" ("FK_ID_USUARIO_FINAL", "USADO");
CREATE INDEX IF NOT EXISTS idx_pago_pedido ON "hot_click_pago_tb" ("fk_id_pedido");
CREATE INDEX IF NOT EXISTS idx_pago_merchant ON "hot_click_pago_tb" ("merchant_token");
CREATE INDEX IF NOT EXISTS idx_txn_pago ON "hot_click_transaccion_pago_tb" ("fk_id_pago");

-- ============================================================
-- TRIGGERS
-- ============================================================
CREATE OR REPLACE FUNCTION fn_validar_stock_carrito()
RETURNS TRIGGER AS $$
DECLARE
    v_stock_actual INTEGER;
    v_es_unico BOOLEAN;
    v_vendido BOOLEAN;
BEGIN
    SELECT stock_actual, es_unico, vendido
    INTO v_stock_actual, v_es_unico, v_vendido
    FROM "HOT_CLICK_PRODUCTO_TB"
    WHERE id_producto = NEW.fk_id_producto;

    IF v_es_unico AND v_vendido THEN
        RAISE EXCEPTION 'Este artículo único ya fue vendido';
    END IF;

    IF NEW.cantidad > v_stock_actual THEN
        RAISE EXCEPTION 'Stock insuficiente. Disponible: %', v_stock_actual;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tg_validar_stock_carrito
    BEFORE INSERT OR UPDATE ON "HOT_CLICK_CARRITO_ITEM_TB"
    FOR EACH ROW EXECUTE FUNCTION fn_validar_stock_carrito();

CREATE OR REPLACE FUNCTION fn_marcar_unico_vendido()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE "HOT_CLICK_PRODUCTO_TB"
    SET vendido = true, stock_actual = 0, visible_catalogo = false
    WHERE id_producto = NEW.fk_id_producto AND es_unico = true;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tg_marcar_unico_vendido
    AFTER INSERT ON "HOT_CLICK_PEDIDO_ITEM_TB"
    FOR EACH ROW EXECUTE FUNCTION fn_marcar_unico_vendido();

CREATE OR REPLACE FUNCTION fn_actualizar_total_carrito()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE "HOT_CLICK_CARRITO_TB"
    SET total_carrito = (
        SELECT COALESCE(SUM(cantidad * precio_unitario_momento), 0)
        FROM "HOT_CLICK_CARRITO_ITEM_TB"
        WHERE fk_id_carrito = COALESCE(NEW.fk_id_carrito, OLD.fk_id_carrito)
          AND fk_id_estado = 1
    ), fecha_actualizacion = CURRENT_TIMESTAMP
    WHERE id_carrito = COALESCE(NEW.fk_id_carrito, OLD.fk_id_carrito);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tg_actualizar_total_carrito
    AFTER INSERT OR UPDATE OR DELETE ON "HOT_CLICK_CARRITO_ITEM_TB"
    FOR EACH ROW EXECUTE FUNCTION fn_actualizar_total_carrito();

-- ============================================================
-- FUNCIONES PARA PAGOS
-- ============================================================
CREATE OR REPLACE FUNCTION fn_crear_pago(
    p_id_pedido BIGINT,
    p_id_usuario INTEGER,
    p_monto INTEGER,
    p_moneda VARCHAR(3) DEFAULT 'CRC',
    p_metodo_pago_tipo VARCHAR(30) DEFAULT 'PAYXPERT_TARJETA',
    p_redirect_url VARCHAR(1000) DEFAULT NULL
) RETURNS TABLE(
    id_pago BIGINT,
    merchant_token VARCHAR(500),
    monto INTEGER,
    moneda VARCHAR(3),
    redirect_url VARCHAR(1000)
) AS $$
DECLARE
    v_merchant_token VARCHAR(500);
    v_id_pago BIGINT;
BEGIN
    v_merchant_token := 'PAYXPERT-' || UPPER(SUBSTRING(MD5(RANDOM()::TEXT || EXTRACT(EPOCH FROM NOW())::TEXT), 1, 32));
    
    INSERT INTO hot_click_pago_tb (
        merchant_token, redirect_url, monto, moneda, estado_pago, metodo_pago_tipo,
        fecha_expiracion, fk_id_pedido, fk_id_usuario, fk_id_estado
    ) VALUES (
        v_merchant_token, p_redirect_url, p_monto, p_moneda, 'PENDIENTE', p_metodo_pago_tipo,
        CURRENT_TIMESTAMP + INTERVAL '2 hours', p_id_pedido, p_id_usuario, 1
    ) RETURNING id_pago INTO v_id_pago;
    
    RETURN QUERY SELECT p.id_pago, p.merchant_token, p.monto, p.moneda, p.redirect_url
    FROM hot_click_pago_tb p WHERE p.id_pago = v_id_pago;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION fn_obtener_pago_por_token(
    p_merchant_token VARCHAR(500)
) RETURNS TABLE(
    id_pago BIGINT, merchant_token VARCHAR(500), monto INTEGER, moneda VARCHAR(3),
    estado_pago VARCHAR(30), metodo_pago_tipo VARCHAR(30), fecha_creacion TIMESTAMP,
    fecha_expiracion TIMESTAMP, id_pedido BIGINT, numero_pedido VARCHAR(20),
    total_pedido INTEGER, nombre_usuario VARCHAR(100), correo_usuario VARCHAR(100)
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        p.id_pago, p.merchant_token, p.monto, p.moneda, p.estado_pago, p.metodo_pago_tipo,
        p.fecha_creacion, p.fecha_expiracion, ped.id_pedido, ped.numero_pedido,
        ped.total_pedido, u.nombre || ' ' || u.apellido_paterno, u.correo
    FROM hot_click_pago_tb p
    JOIN HOT_CLICK_PEDIDO_TB ped ON p.fk_id_pedido = ped.id_pedido
    JOIN HOT_CLICK_USUARIO_TB u ON p.fk_id_usuario = u.id_usuario
    WHERE p.merchant_token = p_merchant_token AND p.fk_id_estado = 1;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ============================================================
-- DATOS INICIALES
-- ============================================================
BEGIN;

INSERT INTO "HOT_CLICK_ESTADO_TB" ("ID_ESTADO", "NOMBRE_ESTADO", "DESCRIPCION", "CODIGO_COLOR") VALUES
  (1, 'ACTIVO', 'Registro activo y funcional', '#00FF00'),
  (2, 'INACTIVO', 'Registro desactivado', '#FFA500'),
  (3, 'ELIMINADO', 'Registro eliminado logicamente', '#FF0000'),
  (4, 'SUSPENDIDO', 'Registro suspendido temporalmente', '#FFFF00')
ON CONFLICT ("ID_ESTADO") DO NOTHING;

INSERT INTO "HOT_CLICK_ROL_TB" ("ID_ROL", "NOMBRE_ROL", "DESCRIPCION", "NIVEL_ACCESO") VALUES
  (1, 'ADMIN_IT', 'Administrador del sistema - control total', 10),
  (2, 'ADMIN_CLIENTE', 'Administrador de negocio - gestion propia', 5),
  (3, 'USUARIO_FINAL', 'Cliente registrado', 1)
ON CONFLICT ("ID_ROL") DO NOTHING;

INSERT INTO "HOT_CLICK_METODO_PAGO_CONFIG_TB" ("ID_METODO_PAGO_CONFIG", "NOMBRE", "ACTIVO", "ORDEN") VALUES
  (1, 'TARJETA_CREDITO', TRUE, 1),
  (2, 'SINPE_MOVIL', TRUE, 2),
  (3, 'EFECTIVO_ENTREGA', TRUE, 3),
  (4, 'PAYXPERT_TARJETA', TRUE, 4),
  (5, 'PAYXPERT_APPLE_PAY', FALSE, 5)
ON CONFLICT ("ID_METODO_PAGO_CONFIG") DO UPDATE SET
    "NOMBRE" = EXCLUDED."NOMBRE", "ACTIVO" = EXCLUDED."ACTIVO", "ORDEN" = EXCLUDED."ORDEN";

INSERT INTO "HOT_CLICK_USUARIO_TB" ("ID_USUARIO", "IDENTIFICACION", "NOMBRE", "APELLIDO_PATERNO", "CORREO", "TELEFONO", "CONTRASENA_HASH") VALUES
  (1, '999999999', 'Admin', 'Sistema', 'admin@hotclick.com', '88888888', '$2b$10$placeholder')
ON CONFLICT ("ID_USUARIO") DO NOTHING;

INSERT INTO "HOT_CLICK_USUARIO_ROL_TB" ("FK_ID_USUARIO", "FK_ID_ROL") VALUES (1, 1)
ON CONFLICT ("FK_ID_USUARIO", "FK_ID_ROL") DO NOTHING;

COMMIT;

-- ============================================================
-- FIN DEL SCRIPT
-- ============================================================