services:
  hot_click_outlet:
    image: hotclick-outlet:latest
    container_name: hot_click_outlet
    env_file: .env
    ports:
      - "8080:8080"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: unless-stopped
