services:
  - type: web
    name: hot-click-backend
    runtime: docker
    rootDir: ./Hot_click_outlet
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: MAIL_PASSWORD
        sync: false
