import { IconPhone, IconCash, IconCard, IconRapido, IconNormalGam, IconFueraGam, IconEncomienda, IconInternacional } from './enviosIcons'

/** Métodos de pago mostrados en el hero. */
export const paymentMethods = [
  { label: 'SINPE Móvil', Icon: IconPhone, active: true },
  { label: 'Efectivo', Icon: IconCash, active: true },
  { label: 'Tarjeta', Icon: IconCard, active: false, tag: 'próximo' },
]

/** Opciones de envío de la página. No alterar copy ni precios. */
export const services = [
  {
    id: 'rapido',
    icon: <IconRapido />,
    name: 'Envío Rápido',
    badge: 'Próximamente',
    badgeType: 'soon',
    time: '30 min – 2 horas',
    desc: 'Mensajero en moto directo a tu puerta dentro del Gran Área Metropolitana. Pago previo requerido.',
    price: null,
    priceSub: null,
    payment: [{ label: 'SINPE Móvil', Icon: IconPhone }],
    active: false,
    color: '#f59e0b',
  },
  {
    id: 'normal-gam',
    icon: <IconNormalGam />,
    name: 'Envío Normal — GAM',
    badge: 'Servicio oficial',
    badgeType: 'official',
    time: '2–4 días hábiles',
    desc: 'Correos de Costa Rica a San José, Heredia, Alajuela y Cartago. Número de rastreo incluido.',
    price: '~₡4,000',
    priceSub: 'Estimado · puede variar',
    payment: [{ label: 'SINPE Móvil', Icon: IconPhone }, { label: 'Efectivo', Icon: IconCash }],
    paymentNote: 'Contra entrega',
    active: true,
    color: 'var(--hc-accent)',
  },
  {
    id: 'fuera-gam',
    icon: <IconFueraGam />,
    name: 'Fuera de la GAM',
    badge: 'Servicio oficial',
    badgeType: 'official',
    time: '3–4 días hábiles',
    desc: 'Correos de Costa Rica a Guanacaste, Puntarenas, Limón y zonas rurales. Rastreo incluido.',
    price: '~₡4,000',
    priceSub: 'Estimado · puede variar',
    payment: [{ label: 'SINPE Móvil', Icon: IconPhone }, { label: 'Efectivo', Icon: IconCash }],
    paymentNote: 'Contra entrega',
    active: true,
    color: 'var(--hc-accent)',
  },
  {
    id: 'encomienda',
    icon: <IconEncomienda />,
    name: 'Tu encomienda',
    badge: 'Próximamente',
    badgeType: 'soon',
    time: 'Según tu mensajero',
    desc: 'Coordinamos con el mensajero que vos elegís. HOTCLICK cubre la gestión; la tarifa del courier va aparte.',
    price: '₡2,500 + tarifa encomienda',
    priceSub: 'Costo HOTCLICK · tarifa del courier aparte',
    payment: [{ label: 'SINPE Móvil', Icon: IconPhone }],
    active: false,
    color: '#8b5cf6',
  },
  {
    id: 'internacional',
    icon: <IconInternacional />,
    name: 'Internacional',
    badge: 'Servicio oficial',
    badgeType: 'official',
    time: 'A coordinar',
    desc: 'Enviamos a cualquier país. Tiempo y costo se coordinan directamente según destino y peso.',
    price: 'Consultar',
    priceSub: null,
    payment: [{ label: 'SINPE Móvil', Icon: IconPhone }],
    active: true,
    color: 'var(--hc-accent)',
    cta: { label: 'WhatsApp →', href: 'https://wa.me/50686667888?text=Hola,%20me%20interesa%20un%20envío%20internacional' },
  },
]
