/**
 * Arma las props de ProductosPageView desde el estado de la página.
 * @param {object} ctx
 */
export function toProductosPageViewProps(ctx) {
  const {
    t,
    isAdmin,
    loadError,
    loading,
    load,
    prodPage,
    filtered,
    totalProds,
    products,
    bodegas,
    categories,
    marcas,
    handleImportBulk,
    openNew,
    openEdit,
    carruselSlots,
    carruselOpen,
    setCarruselOpen,
    handleCarruselMover,
    handleToggleCarrusel,
    handleToggleDestacado,
    propsFiltros,
    debouncedSearch,
    search,
    onSearch,
    handleDelete,
    handleSave,
    confirmDelete,
    handleModalClose,
    modalOpen,
    setModalOpen,
    form,
    setForm,
    editing,
    saving,
    seoOpen,
    setSeoOpen,
    seoAutoTitle,
    setSeoAutoTitle,
    seoAutoDesc,
    setSeoAutoDesc,
    showDiscardModal,
    setShowDiscardModal,
    deleteTarget,
    setDeleteTarget,
    kardexProducto,
    setKardexProducto,
    editInitialFormRef,
    clearFilters,
    hasFilters,
    setProdPage,
  } = ctx

  return {
    loadError,
    loading,
    onRetry: () => load(prodPage),
    header: {
      t,
      filteredCount: filtered.length,
      totalProds,
      products,
      bodegas,
      onImport: handleImportBulk,
      onNuevo: openNew,
      vistaSimple: ctx.vistaSimple,
    },
    carrusel: {
      isAdmin,
      slots: carruselSlots,
      open: carruselOpen,
      onToggleOpen: () => setCarruselOpen((o) => !o),
      onMover: handleCarruselMover,
      onQuitar: handleToggleCarrusel,
    },
    listado: {
      propsFiltros,
      debouncedSearch,
      totalProds,
      search,
      onSearch,
      loading,
      filtered,
      products,
      prodPage,
      isAdmin,
      carruselSlots,
      hasFilters,
      onToggleDestacado: handleToggleDestacado,
      onToggleCarrusel: handleToggleCarrusel,
      onEdit: openEdit,
      onKardex: setKardexProducto,
      onDelete: handleDelete,
      onOferta: ctx.handleOfertaRapida,
      onOcultar: ctx.handleOcultar,
      onClearFilters: clearFilters,
      onNuevo: openNew,
      onPage: setProdPage,
      vistaSimple: ctx.vistaSimple,
    },
    formModal: {
      open: modalOpen,
      onClose: handleModalClose,
      form,
      setForm,
      categories,
      bodegas,
      marcas,
      editing,
      saving,
      seoOpen,
      setSeoOpen,
      seoAutoTitle,
      setSeoAutoTitle,
      seoAutoDesc,
      setSeoAutoDesc,
      onSubmit: handleSave,
      setModalOpen,
    },
    confirms: {
      showDiscardModal,
      onCloseDiscard: () => setShowDiscardModal(false),
      onConfirmDiscard: () => { setShowDiscardModal(false); setModalOpen(false); editInitialFormRef.current = null },
      deleteTarget,
      onCloseDelete: () => setDeleteTarget(null),
      onConfirmDelete: confirmDelete,
      kardexProducto,
      onCloseKardex: () => setKardexProducto(null),
    },
  }
}
